### ISSUE TITLE
AOT NOT support

### ISSUE THREAD

**Issue by sandrola** [pbhogan/TinyJSON#8] opened 2016-02-02 02:55 UTC
Excellent jobs first. 

But I encounter some issue while running under ios && webgl . I'm using Unity 5.3.1 , script backend is IL2CPP. Error said "Attempting to call method 'TinyJSON.JSON::DecodeType' for which no ahead of time (AOT) code was generated" while trying to deserialize properties . 

This tool is awesome but since the issue above I have to find other alternatives. Hope you guys can fix this one , thanks in advanced.

**Comment by ByronMayne** [comment] 2016-02-02 03:16
When we used the source we had to add a bunch of preserve attributes above the problem functions. The AOT support function gets stripped too with Il2CPP

**Comment by sandrola** [comment] 2016-02-02 03:45
@ByronMayne  Thanks for your response.

So what you mean is there is no solution to this? or I can add preserve attributes to work around?

**Comment by ByronMayne** [comment] 2016-02-02 04:13
The issue is the Dll gets stripped  twice. Once for the C# code. Inside TinyJSON code there are functions that try to stop this. The issues is IL2CPP then strips the IL again when it's being converted into C++. You have to tell Unity to not do this. I can add the support to my fork then ask for it to be merged in.

**Comment by pbhogan** [comment] 2016-02-02 15:29
I'm not too familiar with IL2CPP so I'd be happy to merge a patch that addresses this. :)

**Comment by ByronMayne** [comment] 2016-02-02 18:20
It's a super quick fix!

My fork has quite a bit of content added to it that might not be desired. I would suggest update the changes on your end instead of merging. However it should only take a few minutes and you can see what I did in my commit below. 

https://github.com/ByronMayne/TinyJSON/commit/fef9134cfbdbf035b2db899262e04a8701ac4fa3

Cheers :)

**Comment by pbhogan** [comment] 2016-02-03 02:10
Okay this should hopefully be fixed by 56c4042623c1759302a6abbf5a317b3243206664

**Closed by pbhogan** 2016-02-03 02:10 UTC
